### ISSUE TITLE
Add on Packagist?

### ISSUE THREAD

**Issue by TomasVotruba** [ircmaxell/PHP-Yacc#6]
I'd :heart:  to use this, could you add it please? 

https://packagist.org/packages/submit

**Comment by TiMESPLiNTER** [comment]
In the meantime you can use it like this:

**composer.json**
```json
{
    "repositories": [
        {"type": "vcs", "no-api": true, "url": "https://github.com/ircmaxell/PHP-Yacc.git"}
    ],
    "require": {
        "ircmaxell/php-yacc": "dev-master"
    },
}
```

**Comment by adaamz** [comment]
any update? @ircmaxell ?

**Comment by ircmaxell** [comment]
Done, sorry about that, didn't notice this issue. https://packagist.org/packages/ircmaxell/php-yacc

**Comment by TomasVotruba** [comment]
Thank you
